import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Ticket = { id:string; epic:string; block:string; scope:string; path:string; deps:string[]; files:string[]; accept:string[]; days:number };
type RecordState = { id:string; status:string; attempts:number; reason?:string; model?:string; effort?:string; commit?:string; branch?:string; updatedAt:string; usage?:{input:number;cached:number;output:number} };
type Route = {model:string;effort:string;reason:string};
type Payload = {
  tickets:Ticket[]; snapshot:{paused:boolean;tickets:Record<string,RecordState>;events:{id?:string;ticketId?:string;type?:string;status?:string;at?:string;timestamp?:string;reason?:string;message?:string}[];updatedAt:string};
  routes:Record<string,Route>; ready:string[]; active:number; started:number; limit:number; branch:string;
  maxWorkers:number; observedTokens:number; tokenLimit:number; publish:boolean; token:string; mode:string;
};
const labels:Record<string,string> = {pending:'Queued',running:'Building',checking:'Checking',reviewing:'Reviewing',integrating:'Integrating',done:'Complete',needs_attention:'Needs attention'};
const activeStatuses = ['running','checking','reviewing','integrating'];
function shortModel(model:string) { return model.replace('gpt-5.6-','').replace('gpt-6-',''); }
function App() {
 const [data,setData] = useState<Payload|null>(null);
 const [online,setOnline] = useState(false);
 const [error,setError] = useState('');
 const [query,setQuery] = useState('');
 const [filter,setFilter] = useState('all');
 const [selected,setSelected] = useState<string|null>('F01');
 const [view,setView] = useState<'board'|'map'|'models'>('board');
 const [pending,setPending] = useState(false);
 useEffect(() => {
   const stream = new EventSource('/api/events');
   stream.onmessage = event => {try {setData(JSON.parse(event.data));setOnline(true);} catch {setError('Invalid update received. Reload to reconnect.');}};
   stream.onerror = () => setOnline(false);
   return () => stream.close();
 },[]);
 async function action(action:string,id?:string) {
   if(!data || pending) return;
   setPending(true);setError('');
   try {const response=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json','X-Runner-Token':data.token},body:JSON.stringify({action,...(id?{id}:{})})});const result=await response.json();if(!response.ok)throw new Error(result.error ?? 'Request failed');}
   catch(error){setError(error instanceof Error?error.message:'Request failed');}
   finally{setPending(false);}
 }
 if(!data)return <main className="loading"><div className="logo">e<span>p</span></div><h1>Connecting to Build Control</h1><p>Loading the local ticket ledger…</p>{!online&&<small>The runner must be running on this computer.</small>}</main>;
 const records=Object.values(data.snapshot.tickets);
 const complete=records.filter(r=>r.status==='done').length;
 const attention=records.filter(r=>r.status==='needs_attention').length;
 const progress=Math.round(complete/data.tickets.length*100);
 const visible=data.tickets.filter(t=>`${t.id} ${t.epic} ${t.scope} ${t.path}`.toLowerCase().includes(query.toLowerCase()) && (filter==='all'||(filter==='ready'?data.ready.includes(t.id):data.snapshot.tickets[t.id]?.status===filter)));
 const ticket=data.tickets.find(t=>t.id===selected);
 const record=ticket?data.snapshot.tickets[ticket.id]:null;
 const groups=[{key:'pending',name:'Up next',statuses:['pending']},{key:'running',name:'In motion',statuses:activeStatuses},{key:'needs_attention',name:'Needs attention',statuses:['needs_attention']},{key:'done',name:'Shipped',statuses:['done']}];
 const status=(id:string)=>data.snapshot.tickets[id]?.status??'pending';
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="/"><div className="logo">e<span>p</span></div><div>EchoPilot<small>BUILD CONTROL</small></div></a><div className="workspace"><span className="green-dot"/>Local workspace<small>{data.branch}</small></div><nav aria-label="Dashboard views">{([['board','▦','Ticket board'],['map','◈','Dependency map'],['models','◎','Model strategy']] as const).map(([key,icon,title])=><button key={key} className={view===key?'nav active':'nav'} onClick={()=>setView(key)}><span>{icon}</span>{title}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><span className={online?'green-dot':'red-dot'}/>{online?'Live updates connected':'Reconnecting…'}</div><p>Fresh context. Focused work.<br/>Every transition recorded.</p><small>Loopback only · No hosted service</small></div></aside>
  <main className="main"><header className="topbar"><div><span className="eyebrow">PROJECT / ECHOPILOT</span><h1>{view==='board'?'From plan to progress.':view==='map'?'See what unlocks next.':'The right model for the work.'}</h1><p>{view==='models'?'Explainable starting rules, refined by actual acceptance and rework.':'One coherent slice at a time. Follow workers, reviews, and the path to delivery.'}</p></div><span className={`run-status ${data.snapshot.paused?'paused':'live'}`}><i/>{data.snapshot.paused?'Loop paused':'Loop running'}</span></header>
  <section className="metrics" aria-label="Progress overview"><article><span>Tickets complete</span><strong>{complete}<em> / {data.tickets.length}</em></strong><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{progress}% accepted and integrated</small></article><article><span>Worker slots</span><strong>{data.active}<em> / {data.maxWorkers}</em></strong><div className="slots">{Array.from({length:data.maxWorkers},(_,i)=><i key={i} className={i<data.active?'occupied':''}/>)}</div><small>One separate reviewer at a time</small></article><article><span>Ready to build</span><strong>{data.ready.length}</strong><small>{attention?`${attention} ticket${attention===1?'':'s'} need attention`:'Dependencies and file locks checked'}</small></article><article><span>Observed tokens · this run</span><strong>{(data.observedTokens/1000).toFixed(1)}<em> k</em></strong><small>{data.started}/{data.limit} starts · {(data.tokenLimit/1000).toLocaleString()}k scheduling ceiling</small></article></section>
  <section className="command-bar"><div><span className="green-dot"/><strong>{data.publish?'GitHub publication enabled':'Local commits only'}</strong><span>Reviewed commits → {data.branch}</span></div><div className="actions"><button disabled={pending||!online} onClick={()=>void action(data.snapshot.paused?'resume':'pause')} className="primary">{data.snapshot.paused?'▶ Start loop':'Ⅱ Pause new work'}</button><button disabled={pending||!online||data.active===0} onClick={()=>void action('stop')} className="stop">Stop workers</button></div></section>
  {error&&<div className="error" role="alert">{error}</div>}
  {view==='models'?<section className="model-view"><div className="model-intro"><span className="eyebrow">COST-CONSCIOUS BY DESIGN</span><h2>Capability where it earns its keep.</h2><p>Luna handles bounded work. Terra owns normal implementation and hard interfaces. Sol reviews changes and handles security-sensitive work. Astra is never selected by the default policy.</p><p>Medium effort is the starting point; high effort is reserved for coupled logic and review. These are hypotheses, not measured task-specific rankings.</p></div><div className="model-grid">{['luna','terra','sol'].map(m=>{const assigned=data.tickets.filter(t=>data.routes[t.id]?.model.endsWith(m));return <article key={m}><span className={`model-mark ${m}`}>◎</span><h3>GPT-5.6 {m[0]!.toUpperCase()+m.slice(1)}</h3><p>{m==='luna'?'Bounded UI, documentation, and small evaluation work.':m==='terra'?'Everyday implementation, state machines, interfaces, and memory.':'Independent reviews and permission/security-sensitive implementation.'}</p><strong>{assigned.length} tickets</strong><small>Initial implementation assignments</small></article>;})}</div><div className="model-table"><h2>Per-ticket assignment</h2>{data.tickets.map(t=><button className="model-row" key={t.id} onClick={()=>{setSelected(t.id);setView('board');}}><b>{t.id}</b><span>{t.epic.replace('E-','')}</span><span className="model-tag">{shortModel(data.routes[t.id]?.model??'unknown')} · {data.routes[t.id]?.effort}</span><small>{data.routes[t.id]?.reason}</small></button>)}</div><div className="note">Token totals come from CLI usage events and can lag in-flight work. They are not a dollar invoice or a hard spending cap. Track accepted tickets and retries before changing model assignments.</div></section>:
  <><section className="board-toolbar"><div className="tabs"><button className={filter==='all'?'chosen':''} onClick={()=>setFilter('all')}>All tickets <b>{data.tickets.length}</b></button><button className={filter==='ready'?'chosen':''} onClick={()=>setFilter('ready')}>Ready now <b>{data.ready.length}</b></button><button className={filter==='needs_attention'?'chosen':''} onClick={()=>setFilter('needs_attention')}>Attention <b>{attention}</b></button></div><input aria-label="Search tickets" placeholder="Search tickets, epics, or scope…" value={query} onChange={e=>setQuery(e.target.value)}/></section>
  <div className="work-area"><div className="board-area">{view==='map'?<section className="dependency-map">{visible.map(t=><button key={t.id} className={`dependency-node ${status(t.id)} ${selected===t.id?'selected':''}`} onClick={()=>setSelected(t.id)}><span className="node-id">{t.id}<i className={data.ready.includes(t.id)?'ready-dot':''}/></span><strong>{t.epic.replace('E-','')}</strong><small>{t.deps.length?'REQUIRES':'STARTING POINT'}</small><div>{t.deps.map(dep=><span key={dep} className={status(dep)==='done'?'dep done':'dep'}>{status(dep)==='done'?'✓ ':''}{dep}</span>)}</div><p>{labels[status(t.id)]}</p></button>)}</section>:<section className="kanban">{groups.map(group=>{const cards=visible.filter(t=>group.statuses.includes(status(t.id)));return <div className={`column ${group.key}`} key={group.key}><h2><i/>{group.name}<span>{cards.length}</span></h2><div className="card-stack">{cards.map(t=>{const r=data.snapshot.tickets[t.id]!;const route=data.routes[t.id]!;return <button key={t.id} className={`ticket-card ${selected===t.id?'selected':''}`} onClick={()=>setSelected(t.id)}><div className="card-top"><strong>{t.id}</strong><span>{t.epic.replace('E-','')}</span></div><h3>{t.path}</h3><div className="card-tags"><span className="model-tag">{shortModel(r.model??route.model)} · {r.effort??route.effort}</span>{data.ready.includes(t.id)&&<span className="ready-tag">Ready</span>}</div><div className="card-footer"><span>{r.attempts?`Attempt ${r.attempts}`:t.deps.length?`${t.deps.filter(id=>status(id)!=='done').length} dependencies left`:'No dependencies'}</span><span>{activeStatuses.includes(r.status)?labels[r.status]:`${t.days}d scope`}</span></div></button>;})}{!cards.length&&<p className="empty-column">{group.key==='done'?'Accepted work will land here.':group.key==='running'?'Workers appear when the loop starts.':'No tickets in this view.'}</p>}</div></div>;})}</section>}</div>
  {ticket&&record&&<aside className="detail"><div className="detail-top"><span className="eyebrow">TICKET DETAILS</span><button aria-label="Close ticket details" onClick={()=>setSelected(null)}>×</button></div><div className="detail-title"><h2>{ticket.id}</h2><span className={`status-pill ${record.status}`}>{labels[record.status]}</span></div><h3>{ticket.path}</h3><p>{ticket.scope}</p><div className="detail-route"><span>Assigned model</span><strong>{record.model??data.routes[ticket.id]?.model}</strong><small>{record.effort??data.routes[ticket.id]?.effort} effort · {data.routes[ticket.id]?.reason}</small></div><h4>Acceptance criteria</h4><ul className="criteria">{ticket.accept.map((a,i)=><li key={i}><span>{record.status==='done'?'✓':'○'}</span>{a}</li>)}</ul><h4>Dependencies</h4><div className="dependencies">{ticket.deps.length?ticket.deps.map(id=><button key={id} className={status(id)==='done'?'done':''} onClick={()=>setSelected(id)}>{status(id)==='done'?'✓':'↳'} {id}</button>):<small>Ready from the start</small>}</div><h4>Latest update</h4><p className="latest-reason">{record.reason??(ticket.id==='F01'?'Bootstrap already exists. Remaining contracts and adapters still need completion.':'Waiting for dependencies and an available worker.')}</p>{record.commit&&<p className="commit">Commit {record.commit.slice(0,8)}</p>}{record.status==='needs_attention'&&<button className="retry" disabled={pending} onClick={()=>void action('retry',ticket.id)}>Requeue within attempt limit</button>}<details><summary>Owned paths</summary>{ticket.files.map(f=><code key={f}>{f}</code>)}</details></aside>}
  </div></>}
  <section className="activity"><div className="activity-heading"><h2>Live activity</h2><span>{online?'STREAMING':'RECONNECTING'}</span></div>{data.snapshot.events.length?[...data.snapshot.events].reverse().slice(0,10).map((event,i)=><div className="activity-row" key={event.id??i}><time>{new Date(event.at??event.timestamp??data.snapshot.updatedAt).toLocaleTimeString()}</time><b>{event.ticketId??'SYSTEM'}</b><span>{event.reason??event.message??event.type??event.status}</span></div>):<div className="empty-activity">The ledger is ready. Start the loop to see work move through build, checks, review, and integration.</div>}</section>
  <footer>EchoPilot Build Control <span>Local state · Fresh worker contexts · Bounded retries</span></footer>
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
